version: "3.8"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - elasticsearch
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node

volumes:
  mongodb_data:
